/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webtools;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author gdaru
 */
public class CompressJS extends javax.swing.JFrame {

    /**
     * Creates new form CompressJS
     */
    File[] files;
    public CompressJS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_jsSavePath = new javax.swing.JTextField();
        lbl_savePath = new javax.swing.JLabel();
        btn_chooseSavePath = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        lbl_arquivos = new javax.swing.JLabel();
        lbl_fileList = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_status = new javax.swing.JLabel();
        lbl_fileList1 = new javax.swing.JLabel();
        lbl_jsStatusFiles = new javax.swing.JLabel();
        btn_jsFiles = new javax.swing.JButton();
        btn_jsCompress = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_jsSavePath.setEnabled(false);

        lbl_savePath.setText("Save Path");

        btn_chooseSavePath.setText("...");
        btn_chooseSavePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chooseSavePathActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_arquivos.setText("Files");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_arquivos)
                    .addComponent(lbl_fileList))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_arquivos)
                .addGap(34, 34, 34)
                .addComponent(lbl_fileList)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_status.setText("Status");

        lbl_jsStatusFiles.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_jsStatusFiles)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_status)
                            .addComponent(lbl_fileList1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_jsStatusFiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_fileList1)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        btn_jsFiles.setText("Select Files");
        btn_jsFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jsFilesActionPerformed(evt);
            }
        });

        btn_jsCompress.setText("Compress");
        btn_jsCompress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jsCompressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_jsFiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_jsCompress)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_savePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_jsSavePath, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chooseSavePath)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_savePath)
                    .addComponent(txt_jsSavePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chooseSavePath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_jsFiles)
                    .addComponent(btn_jsCompress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chooseSavePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chooseSavePathActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Destiny Folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.showDialog(this, "Ok");
        txt_jsSavePath.setText(chooser.getSelectedFile().getAbsolutePath());
        txt_jsSavePath.setEnabled(false);

    }//GEN-LAST:event_btn_chooseSavePathActionPerformed

    private void btn_jsFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jsFilesActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc    = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("JavaScript", "js");
        jfc.setFileFilter(fnef);
        jfc.setMultiSelectionEnabled(true);

        jfc.showDialog(this, "Ok");
        files = jfc.getSelectedFiles();
        String html = "<html>";
        for(int i = 0; i<files.length;i++)
        {
            html = html + files[i].getName().toString()+"<br />";
        }
        html = html + "</html>";
        lbl_fileList.setText(html);
    }//GEN-LAST:event_btn_jsFilesActionPerformed

    private void btn_jsCompressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jsCompressActionPerformed
        // TODO add your handling code here:
        try{
            if(files.length > 0)
            {
                String html = "<html>";
                for(int i=0;i<files.length; i++)
                {
                    System.out.println("Convertendo arquivo: " + files[i].getPath());
                    html = html + "Convertendo arquivo: " + files[i].getPath() + "<br />";
                    lbl_jsStatusFiles.setText(html);
                    Compressor cp = new Compressor();

                    if(cp.CompressJS(files[i].getAbsolutePath(), files[i].getName(), txt_jsSavePath.getText()) != 0)
                    {
                        JOptionPane.showMessageDialog(this, "Erro ao comprimir: " + files[i].getName(),"Compression Error",JOptionPane.ERROR_MESSAGE);
                    }
                }
                html = html + "</html>";
                lbl_jsStatusFiles.setText("Completed");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Please select a file","No file Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_jsCompressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompressJS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompressJS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompressJS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompressJS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompressJS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_chooseSavePath;
    private javax.swing.JButton btn_jsCompress;
    private javax.swing.JButton btn_jsFiles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_arquivos;
    private javax.swing.JLabel lbl_fileList;
    private javax.swing.JLabel lbl_fileList1;
    private javax.swing.JLabel lbl_jsStatusFiles;
    private javax.swing.JLabel lbl_savePath;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JTextField txt_jsSavePath;
    // End of variables declaration//GEN-END:variables
}
